- Sources/TarkaUI/Modifiers/View+Modifiers.swift
- Sources/TarkaUI/View Modifiers/BottomMobileButtonBlock.swift
https://github.com/tarkalabs/tarka-ui-kit-ios/assets/105620769/3d860ab6-b801-4e0d-8c9c-4aca4028a8ab
> Handled hide/show for mobileBlockButton

- Sources/TarkaUI/Resources/Colors.xcassets/OnColorsAltHover/Contents.json
- Sources/TarkaUI/Resources/Colors.xcassets/OnColorsAltHover/onPrimaryAltHover.colorset/Contents.json
- Sources/TarkaUI/Styles/Theme/Color+Theme.swift
- Sources/TarkaUI/Styles/Theme/DefaultTheme.swift
- Sources/TarkaUI/Styles/Theme/TUITheme.swift
> Created onPrimaryAltHover in TUITheme

- README.md
- Sources/TarkaUI/Components/Base Components/Tag/TUITag.swift
> Created TUITag

- Sources/TarkaUI/Components/OverlayView/TUIOverlayContentView.swift
Reverts tarkalabs/tarka-ui-kit-ios#94
> Revert "Removed TUIOverlayContentView"

- Sources/TarkaUI/Components/Base Components/Tag/TUITag.swift
> Updated TUITag

- README.md
- Sources/TarkaUI/Components/Base Components/RadioButton/TUIRadioButton.swift
- Sources/TarkaUI/Components/RadioRow/TUIRadioRow.swift
> Created TUIRadioView

- README.md
- Sources/TarkaUI/Components/TabBar/TUITab.swift
- Sources/TarkaUI/Components/TabBar/TUITabBar.swift
- Extracted TUITab from TUITabBar into separate component
- Added support for icon in tabs
> Created TUITab

- Sources/TarkaUI/Components/Base Components/CheckBox/TUICheckBox.swift
- Sources/TarkaUI/Extensions/Image+Extensions.swift
- Updated with imageIconProtocol
> Created ImageIconProtocol

- Sources/TarkaUI/Components/Base Components/CheckBox/TUICheckBox.swift
- Sources/TarkaUI/Extensions/Image+Extensions.swift
- Renamed icon to TUIAssetIcon
> Renamed TUIAssetIcon in Image+Extensions

- Sources/TarkaUI/Components/Base Components/Tag/TUITag.swift
> Replaced with Image for icon in TUITag

- Sources/TarkaUI/Components/Base Components/IconButton/Modifiers/TUIIconButton+Modifiers.swift
- Sources/TarkaUI/Components/Base Components/IconButton/TUIIconButton.swift
> Removed Background Modifier in TUIIconButton

- Sources/TarkaUI/Components/NavigationRow/TUINavigationRow.swift
- Sources/TarkaUI/Resources/Colors.xcassets/Base - Alt/secondaryAltHover.colorset/Contents.json
- Sources/TarkaUI/Styles/Theme/Color+Theme.swift
- Sources/TarkaUI/Styles/Theme/DefaultTheme.swift
- Sources/TarkaUI/Styles/Theme/TUITheme.swift
> Updated TUINavigation Row

- Sources/TarkaUI/Components/Search Bar/TUISearchBar.swift
- Clear only search text when clear button clicked
> Handled Keyboard Focus while Clearing Search Text in TUISearchBar

- Sources/TarkaUI/Components/App Bar/TUIAppTopBar+Enums.swift
- Sources/TarkaUI/Components/App Bar/TUIAppTopBar.swift
- Sources/TarkaUI/Components/Input Field/Components/TUIDateInputFiled.swift
- Sources/TarkaUI/Components/Input Field/Components/TUIInputField.swift
- Sources/TarkaUI/Components/Input Field/Components/TUITextInputField.swift
- Sources/TarkaUI/Components/Input Field/Helper Views/TUIDatePopover.swift
- Sources/TarkaUI/Components/Input Field/Model/TUIInputFieldState.swift
- Sources/TarkaUI/Components/Input Field/Sub components/TUIInputTextContentView.swift
* Observing isFocused on TUITextField
* Supporting attributed title in TUIAppTopBar
> Input text field and App top bar title updates

- Sources/TarkaUI/Components/Base Components/IconButton/TUIIconButton.swift
- Issue fix for disabled button
> Issue Fix for TUIIconButton button action

- Sources/TarkaUI/Components/App Bar/TUIAppBottomBar+Enums.swift
- Sources/TarkaUI/Components/App Bar/TUIAppBottomBar.swift
- Sources/TarkaUI/Components/Base Components/Button/TUIMobileButtonBlock.swift
- Sources/TarkaUI/Components/Base Components/IconButton/Modifiers/TUIIconButton+Modifiers.swift
- Sources/TarkaUI/Components/Base Components/IconButton/TUIIconButton.swift
- Sources/TarkaUI/Components/Menu Item/TUIContextMenuItem.swift
- Sources/TarkaUI/Components/OverlayFooter/TUIMobileOverlayFooter.swift
- Sources/TarkaUI/Components/OverlayFooter/TUIOverlayFooterAction.swift
- Sources/TarkaUI/Components/OverlayHeader/TUIMobileOverlayHeader.swift
- Created TUIAppBottomBar
- Added menu support to TUIIconButton, including in TUIAppTopBar and TUIMobileOverlayHeader
- TUIMobileOverlayFooter custom button style
> TUIAppBottomBar and TUIIconButton changes

- Sources/TarkaUI/Components/OverlayFooter/TUIMobileOverlayFooter.swift
> Removed Background Blur in TUIMobileOverlayFooter

- Sources/TarkaUI/Components/App Bar/TUIAppTopBar.swift
- Sources/TarkaUI/Components/Base Components/IconButton/TUIIconButton.swift
Issue: https://eam360.atlassian.net/browse/IMA-15527
> Fix: TUIAppTopBar icon size issue

- Sources/TarkaUI/Components/Search Bar/TUISearchBarViewModel.swift
- Updated isFocused when SearchBar showing when more than once in UI.
> Issue For SearchBar Auto Focus in TUIAppBar

- Sources/TarkaUI/Components/Search Bar/SearchTextField.swift
https://eam360.atlassian.net/browse/IMA-15543
> set searchTextField placeholder colour as inputTextDim

- Sources/TarkaUI/Modifiers/View+Modifiers.swift
- Sources/TarkaUI/View Modifiers/BottomMobileButtonBlock.swift
Dependent PR:
https://github.com/tarkalabs/eam360-technician-ios/pull/3185
Issue Link: https://eam360.atlassian.net/browse/IMA-15468
> Show done button in safearea when bottom block modifier is used

- Sources/TarkaUI/View Modifiers/BottomMobileButtonBlock.swift
- Added foregroundStyle for done button
> Added ForegroundStyle Color for DoneButton in BottomMobileButtonBlock

- Sources/TarkaUI/Components/Input Field/Helper Views/TUIDatePopover.swift
Technician PR - https://github.com/tarkalabs/eam360-technician-ios/pull/3421
> datecomponents date and time display flag introduced.

- Sources/TarkaUI/Components/Base Components/Chip/TUIChip.swift
> Handled IsPressed State for TUIChip

- Sources/TarkaUI/Components/Base Components/CircularProgressView/TUICircularProgressView.swift
> Removed GeometryReader in TUICirculatProgressView

- Sources/TarkaUI/Components/App Bar/TUIAppTopBar.swift
- Sources/TarkaUI/Components/Search Bar/TUISearchBarViewModel.swift
Dependent by:
Technician PR: https://github.com/tarkalabs/eam360-technician-ios/pull/3581
> Introduced cancel editing public function

- Example/UI Showcase/UI Showcase/DetailView.swift
> Resolved ShowCaseUI Compile in DetailsView
